### ISSUE TITLE
Is there a way to use this without CLI?

### ISSUE THREAD

**Issue by xypaul** [thefrontside/ember-introjs#4]

**Comment by rwwagner90** [comment]
You can manually copy the files into your app, rather than npm or bower installing.

**Comment by fivetanley** [comment]
Sorry, but not at this time. The amount of work I've ended up doing for Ember and it's related libraries is quite involved to get a "publish-compiled-to-bower", and it seems like the way Ember wants you to move to Ember CLI. If you want a tool to help you do that there is https://github.com/fivetanley/ember-cli-migrator.

**Comment by fivetanley** [comment]
I'd be open to a pull request for it, but we'd need access to the bower publishing repo (I'd like to not commit "dist" here.)

**Comment by rwwagner90** [comment]
@fivetanley as a side note, I couldn't even get it to work with ```ember install:addon ember-introjs```. Your install command in the Readme does not appear to be correct either.
