### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by ChALkeR** [thefrontside/ember-introjs#5]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

Your current package size is 24 MiB packed, 131 MiB unpacked. 124 MiB of that are inside the `tmp` dir. I think that this probably got packed to the release by mistake.

See https://github.com/ember-cli/ember-cli/issues/4199 for details.

**Comment by fivetanley** [comment]
Added in https://github.com/thefrontside/ember-introjs/commit/1abd063916315c875491ad16a267cf29c49f9ebb. Thanks!
