### ISSUE TITLE
Installation Error with Ember CLI 1.13.8

### ISSUE THREAD

**Issue by nizmo** [thefrontside/ember-introjs#7]
I'm getting the following errors when I try to install the package:

ember install ember-introjs
version: 1.13.8
Installed packages for tooling via npm.
installing ember-introjs
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by boydkr** [comment]
I get the same error using ember 1.13.15

**Comment by Robdel12** [comment]
This should have been fixed with #9
